using System.Reflection;

namespace BeGenerate.Helpers;

internal static class GeneratedCodeHelpers
{
    public static void AddAutoGeneratedComment(this CodeBuilder code)
    {
        code.Line("// <auto-generated>");
        code.Line("// This code was generated by a tool.");
        code.Line("// </auto-generated>");
    }

    public static void AnnotateGeneratedCode(this CodeBuilder code)
    {
        var assembly = Assembly.GetExecutingAssembly();
        var name = assembly.GetName()
            .Name;
        var version = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()
                          ?.InformationalVersion ??
                      "1.0.0";
        code.Line($"""[System.CodeDom.Compiler.GeneratedCode("{name}", "{version}")]""");
    }
}
